name: Send Notifications

on:
  schedule:
    - cron: '30 3 * * *' # 12:30 JST
    - cron: '0 5 * * *'  # 14:00 JST
    - cron: '0 6 * * *'  # 15:00 JST
    - cron: '0 12 * * *' # 21:00 JST
  workflow_dispatch: # 手動実行用

jobs:
  notify:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          
      - name: Install Dependencies
        run: npm install
        
      - name: Run Notification Script
        env:
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node scripts/send-notification.js
